project:
  type: website
  output-dir: docs

website:
  title: "My Data Science Blog"
  description: "A blog with tutorials about data science topics"
  
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.md
      - text: "Data Visualization"
        href: blog.md
    right:
      - icon: github
        href: https://github.com/your-username
      - icon: linkedin
        href: https://linkedin.com/in/your-profile

  sidebar:
    - title: "Projects"
      contents:
        - projects/index.md
        - projects/eda.qmd
        - projects/data-acquisition.qmd
        - projects/final-project.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true
    css: styles.css
