[project]
name = "blog-assignment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.6",
    "nbclient>=0.10.2",
    "nbformat>=5.10.4",
    "pandas>=2.3.2",
    "pyyaml>=6.0.3",
    "scipy>=1.16.2",
]
